name: PM service CI/CD Pipeline

on:
  push:
    branches:
      - Develop
env:
  DEPLOYMENT_NAME: pm-service
  DEPLOYMENT_HOST: 140.245.213.62
  IMAGE_NAME: sahananjana/devflow-pm_service:v1.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          # username: ${{ secrets.DOCKER_USERNAME }}
          # password: ${{ secrets.DOCKER_PASSWORD }}
          username: sahananjana
          password: nayakenzz

      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }} .

      - name: Push Docker image
        run: |
          docker push ${{ env.IMAGE_NAME }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to SSH Server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ env.DEPLOYMENT_HOST }} << EOF
            # Stop and remove the existing container if it exists
            sudo docker stop ${{ env.DEPLOYMENT_NAME }} || true
            sudo docker rm ${{ env.DEPLOYMENT_NAME }} || true

            # Pull the latest image
            sudo docker pull ${{ env.IMAGE_NAME }}
            
            # Run the new container
            sudo docker run -d --name ${{ env.DEPLOYMENT_NAME }} -p 8003:8003 ${{ env.IMAGE_NAME }}

            # Delete none tagged images
            # sudo docker rmi $(sudo docker images -f "dangling=true" -q)
          EOF
